archetypes/book/support/templates/html.mustache

Fix javascript and css files in mustache templates

fix: javascript and css paths

---

src/Pillar-ExporterCore.package/PRTocBuilderVisitor.class/instance/visitInputFileAnnotation..st
src/Pillar-Model.package/PRTParametrizable.trait/properties.json
src/Pillar-Model.package/PRTocAnnotation.class/class/tag.st
src/Pillar-Model.package/monticello.meta/categories.st
src/Pillar-Project.package/PRProject.class/class/pathToString..st
src/Pillar-Project.package/PRProject.class/instance/build..st
src/Pillar-Project.package/PRProject.class/instance/generateToc.st
src/Pillar-Project.package/PRProject.class/instance/tableOfContents.st
src/Pillar-Tests-ExporterHTML.package/PRHtmlDocumentTest.class/instance/testMustacheTemplateValuesDontContainsToc.st
src/Pillar-Tests-ExporterHTML.package/PRHtmlDocumentTest.class/instance/testMustacheTemplateWithHtmlOutputContainsTocAnnotation.st
src/Pillar-Tests-ExporterHTML.package/PRHtmlDocumentTest.class/instance/testMustacheTemplateWithPdfOutputDontContainsTocAnnotation.st
src/Pillar-Tests-ExporterHTML.package/PRHtmlDocumentTest.class/instance/testMustacheTemplateWithoutTocPropertyDontContainsToc.st

Try to fix toc tests

---

archetypes/book/sample/pillar.conf
archetypes/book/support/templates/html.mustache

Remove parent annotations in html mustache template
- Now mustache is making the lookup

Remove parent annotations

---

src/Pillar-Cli.package/PRServeCommandLineHandler.class/README.md
src/Pillar-Cli.package/PRServeCommandLineHandler.class/class/commandName.st
src/Pillar-Cli.package/PRServeCommandLineHandler.class/instance/activate.st
src/Pillar-Cli.package/PRServeCommandLineHandler.class/properties.json
src/Pillar-Cli.package/PRWatcher.class/README.md
src/Pillar-Cli.package/PRWatcher.class/class/stopAll.st
src/Pillar-Cli.package/PRWatcher.class/instance/generateHtml.st
src/Pillar-Cli.package/PRWatcher.class/instance/logError..st
src/Pillar-Cli.package/PRWatcher.class/instance/project..st
src/Pillar-Cli.package/PRWatcher.class/instance/start.st
src/Pillar-Cli.package/PRWatcher.class/instance/stop.st
src/Pillar-Cli.package/PRWatcher.class/properties.json

for local testing
pillar serve -w

Add serve command

---

src/PetitMarkdown-Core/PPMarkdownGrammar.class.st
src/PetitMarkdown-Core/PRMarkdownParser.class.st
src/PetitMarkdown-Tests/PPMarkdownGrammarTest.class.st
src/PetitMarkdown-Tests/PRMarkdownParserTest.class.st

parses a document with paragraph, headings, codeblocks and emphases

markdown-code-and-codeblock

---

src/Pillar-Core/PRDocumentItem.class.st

Added a tree gt-inspector for Pillar document model
I was missing it when debugging and inspecting in the visitor

gtInspectorSupport

---

src/Pillar-Tests-ExporterCore/PRBuildStrategyTest.class.st

fix: 434
It implied to change the type of files in PRBuildListStrategy, as a set to avoid duplicates.

Valid tests for PRBuildStrategy : all, main and list

---

src/Pillar-Core/PRDocumentSample.class.st
src/Pillar-ExporterRichText/PRRichTextWriterTest.class.st

**Only 2 fail:** strikethrough needs spaces surrounding text & subscript isn't recognized
**Work in progress**

First tests for ExporterRichText

---

src/Pillar-PetitMicroDown/MicroDownSnippetFactory.class.st
src/Pillar-PetitMicroDown/PRMicroDownGrammar.class.st
src/Pillar-PetitMicroDown/PRMicroDownGrammarTest.class.st

**Goal:** taking inspiration from `PetitPillar`, we'll here write tests for **MicroDown** avoiding hard code of markups.

Tests for MicroDown

---

src/Pillar-RichTextRenderer/PRRenderingPresenter.class.st
src/Pillar-RichTextRenderer/package.st

**How it works?**
1. Type your Pillar code in input windows.
2. Parse it.
3. Your preview appears!
**TODO:**
- you should be able to switch the input langage to MicroDown with a CHANGE button
[Watch a screenshot !](https://zupimages.net/up/20/16/j4ks.png)

New tool: a Pillar Editor using RichText

---

src/Pillar-RichTextRenderer-spec2/PREditorPresenter.class.st
src/Pillar-RichTextRenderer-spec2/PRFileManager.class.st

Improving Editor

---

src/Pillar-RichTextRenderer-spec2/PREditorPresenter.class.st

`PREditorPresenter class >> open` to open tool!

Pillar Editor : new file, open and save files

---

src/Pillar-Project/PRProject.class.st

defaultTarget causes bug to execute other cl…ap pillar commands

Fix clap-pillar problem

---

src/Pillar-Cli/ClapPillarArchetypeCommand.class.st
src/Pillar-Cli/ClapPillarUpdateBuildCommand.class.st
src/Pillar-Cli/ClapPillarUpdateTemplateCommand.class.st
src/Pillar-Project/PRProject.class.st

Create "clap pillar updateBuild" to update build/archetypes using parent/archetypes folder

Clap pillar updateBuild is working

---

src/Pillar-Core/PRTParametrizable.trait.st
src/Pillar-ExporterCore/PREnvironmentTransformer.class.st
src/Pillar-ExporterRichText/PRRichTextWriterTest.class.st
src/Pillar-Tests-Model/PRScriptLanguageTest.class.st

Remove unecessary "not" in code.

remove-unecessary-nots

---

scripts/wrappers/pillar
scripts/wrappers/pillar-db
src/Pillar-Project/PRProject.class.st

Use clap command line handler by default in pillar run

Using clap by default

---

src/Pillar-Chrysal/ChrysalPillarConfigurationTest.class.st
src/Pillar-ExporterBeamer/PRBeamerWriter.class.st
src/Pillar-PetitPillarOld/PRPillarParserOld.class.st
src/Pillar-Tests-ExporterCore/PRCleanAnnotationInParagraphTransfomerTest.class.st
src/Pillar-Tests-ExporterEPub/PREPubNavigationMenuWriterTest.class.st
src/Pillar-Tests-ExporterText/PRTemplatedWriterTest.class.st
src/Pillar-Tests-Model/PRScriptTest.class.st

remove-unread-temporaries

---

src/Pillar-ExporterCore/PRScriptFromFile.class.st
src/Pillar-ExporterRichText/PRCodeblockStylerExtensions.class.st

Remove useless initialization methods + some code cleaning

remove-nil-initialization-of-variables-in-initialize-methods

---

src/Pillar-Chrysal/ConfigurationForPillar.class.st
src/Pillar-ExporterCore/PRTitlePrinterSpecification.class.st

Extract assignations from conditionals

extract-assignations-from-conditionals

---

src/Pillar-BookTester/PRCodeblock.extension.st

Extract returns from conditionals.

extract-returns-from-conditionals

---

src/Pillar-BookTester/PRCreateTestsDocument.class.st
src/Pillar-BookTester/PRCreateTestsTarget.class.st
src/Pillar-Cli/ClapPillarGenerateTestsCommand.class.st

**It raises an error in Pharo image!!!!**

Clap pillar generateTests

---

src/Pillar-Cli/ClapPillarCommand.class.st
src/Pillar-Cli/ClapPillarUpdateBuildCommand.class.st

See `ClapPillarCommand >>printVersion: `

Adding '--version' flag to 'pillar' clap command

---

src/Pillar-ExporterMicrodown/PRMicrodownTextualBuilder.class.st
src/Pillar-ExporterMicrodown/PRMicrodownWriter.class.st
src/Pillar-ExporterMicrodown/PRMicrodownWriterTest.class.st

**Warning: see Note3 in INLINE BLOCKS in [MicroDown syntax](https://docs.google.com/document/d/117sdzSwVSNmK8tDvnHGSLDozu7q1OFgOFPYMY2hfZdY/edit)**

Fix lists and formats with new line

---

src/Pillar-Chrysal/ChrysalPillarConfigurationTest.class.st
src/Pillar-Tests-Cli/ClapPillarBuildCommandTest.class.st
src/Pillar-Tests-Core/PRAnchorTest.class.st
src/Pillar-Tests-Core/PRDocumentGroupTest.class.st
src/Pillar-Tests-Core/PRDocumentItemTest.class.st
src/Pillar-Tests-Core/PRObjectTest.class.st
src/Pillar-Tests-ExporterCore/PRCleanAnnotationInParagraphTransfomerTest.class.st
src/Pillar-Tests-ExporterCore/PRDocumentListTransformerTest.class.st
src/Pillar-Tests-ExporterCore/PRTitlePrinterTest.class.st
src/Pillar-Tests-Model/PRAbstractScriptLanguageTest.class.st
src/Pillar-Tests-Model/PRExternalLinkTest.class.st
src/Pillar-Tests-Model/PRHeaderTest.class.st
src/Pillar-Tests-Model/PRInternalLinkTest.class.st
src/Pillar-Tests-Model/PRMailLinkTest.class.st
src/Pillar-Tests-Model/PRRawTest.class.st
src/Pillar-Tests-Model/PRReferenceTest.class.st
src/Pillar-Tests-Model/PRScriptLanguageTest.class.st
src/Pillar-Tests-Model/PRTableCellTest.class.st
src/Pillar-Tests-Model/PRTableRowTest.class.st
src/Pillar-Tests-Model/PRTableTest.class.st
src/Pillar-Tests-Model/PRTextTest.class.st
src/Pillar-Tests-Model/PRTocTest.class.st
src/Pillar-Tests-PetitPillar/PRPillarParserTest.class.st
src/Pillar-Tests-PetitPillarOld/PRPillarParserOldTest.class.st

simplify-equalities

---

src/Pillar-ExporterMarkdown/PRMicrodownOutput.class.st
src/Pillar-ExporterText/PRMicrodownDocument.class.st

Create PRMicrodownDocument, PRMicrodownOutput as PRWritingTarget to add associate clap command

Clap command : pillar build microdown

---

src/Pillar-ExporterRichText/PRRichTextWriterTest.class.st
src/Pillar-Tests-BookTester/PRBookTestGeneratorTest.class.st
src/Pillar-Tests-BookTester/PRBookTesterVisitorMethodDefinitionTest.class.st
src/Pillar-Tests-BookTester/PRBookTesterVisitorRunAnnotationTest.class.st
src/Pillar-Tests-BookTester/PRBookTesterVisitorTest.class.st
src/Pillar-Tests-BookTester/PRScreenshotTransformerTest.class.st
src/Pillar-Tests-BookTester/PRValidatorVisitorTest.class.st
src/Pillar-Tests-ExporterCore/PRDocumentListTransformerTest.class.st
src/Pillar-Tests-ExporterCore/PRDocumentWriterTest.class.st
src/Pillar-Tests-ExporterCore/PRDocumentWriterTest2.class.st
src/Pillar-Tests-ExporterEPub/PREPubNavigationMenuWriterTest.class.st
src/Pillar-Tests-Model/PRReferenceTest.class.st

Use #assertEmpty: assertions giving better logs in case of failure.

use-assertEmpty

---

src/Pillar-Core/PRDocumentItem.class.st
src/Pillar-ExporterCore/PRDocumentListDateSorter.class.st
src/Pillar-ExporterCore/PRDocumentListNameSorter.class.st
src/Pillar-Tests-BookTester/PRBookTestGeneratorTest.class.st
src/Pillar-Tests-BookTester/PRBookTesterVisitorMethodDefinitionTest.class.st
src/Pillar-Tests-BookTester/PRBookTesterVisitorRunAnnotationTest.class.st
src/Pillar-Tests-BookTester/PRValidatorVisitorTest.class.st
src/Pillar-Tests-Cli/ClapPillarBuildCommandTest.class.st
src/Pillar-Tests-ExporterCore/PRBuildStrategyTest.class.st
src/Pillar-Tests-ExporterCore/PRTocBuilderVisitorTest.class.st
src/Pillar-Tests-ExporterHTML/PRHtmlDocumentTest.class.st

Ensure super setUp/tearDown/initialize are called at the right place.

ensure-super-are-called

---

src/Pillar-PetitMicroDown/PRMicroDownParser.class.st
src/Pillar-PetitPillar/PRPillarParser.class.st
src/Pillar-Tests-BookTester/PRCodeblockTest.class.st
src/Pillar-Tests-PetitPillar/PRPillarGrammarTest.class.st

Removes methods only calling super

remove-methods-only-calling-super

---

src/Pillar-ExporterMicrodown/PRMicrodownWriter.class.st

this PR has a link with an orther PR in Microdown
add canvasSetLF to set the builder line at String lf

Convert piller book to microdown book

---

src/Pillar-Core/PRReference.class.st
src/Pillar-ExporterMicrodown/PRMicrodownWriter.class.st
src/Pillar-ExporterMicrodown/PRMicrodownWriterTest.class.st

The link has not a caption because visitLink don't give a block to the builder.
And figure don't work if the reference didn't convert as an url
I change method text which return the reference url to return a String

fix PRMicrodownWriter for link and figure

---

src/Pillar-ExporterMicrodown/PRMicrodownWriter.class.st

- use a backslasher to export in Microdown
- create visit method for PRDefinitionList

use a backslasher to export in Microdown

---

src/Pillar-Cli/ClapPillarBuildCommand.class.st
src/Pillar-Core/PRDocument.class.st
src/Pillar-Core/PRVisitor.class.st
src/Pillar-ExporterCore/PRAbstractOutputDocument.class.st
src/Pillar-ExporterCore/PRUpdateFileInclusionReference.class.st
src/Pillar-ExporterLaTeX/PRPDFDocument.class.st
src/Pillar-Project/PRDocument.extension.st
src/Pillar-Project/PRProject.class.st

Normally this version should be ready for real md integration. 
Now before merging I will add a tag.

Underway integration pillar
